### ISSUE TITLE
doesn't work with next.11

### ISSUE THREAD

**Issue by fxck** [typebytes/ngx-template-streams#11]
```
ERROR in /Users/fxck/www/zeropsmonorepo/node_modules/@typebytes/ngx-template-streams/fesm5/typebytes-ngx-template-streams.js 114:42-59
"export 'ɵNG_COMPONENT_DEF' was not found in '@angular/core'
```

**Comment by d3lm** [comment]
Thanks for posting this issue 🙏 Really appreciate it that you're testing and using this library. How's it going so far? I might have asked this before, but are you using it for a production app?

Regarding the issue, that's cause it was renamed to `ɵNG_COMP_DEF`. Unfortunately it's not yet a public API and that's why this can potentially change in the future again, until it's public.

I'll change it and maybe add a note to the readme that says if you wanna use this with Ivy, you have to be on the latest version. Does that make sense?

**Comment by fxck** [comment]
> Does that make sense?

Sure.

> Are you using it for a production app?

Nope, we are still pretty much pre-alpha.

> How's it going so far

Other than [this](https://github.com/typebytes/ngx-template-streams/issues/8) (might be worth revisiting it, seeing that Mike's HOC @ngrx/component proof of concept is very similar to what I'm doing), great.

**Comment by d3lm** [comment]
Thanks for the feedback! I ll definitely revisit this soon.

**Comment by fxck** [comment]
Hey, want me to make a PR? Would really like to give the RC a try..

**Comment by d3lm** [comment]
Just noticed that we need to bump the version as well, otherwise the tests fail. I ll do that and commit my changes.

**Comment by d3lm** [comment]
At least for the main app. The lib could still stay on 8 for now I guess.
